// packages/ui-vue/src/components/Button.vue
<template>
  <button
    :class="buttonClasses"
    v-bind="$attrs"
    @click="handleClick"
    ref="buttonRef"
  >
    <slot />
  </button>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { ButtonProps, styleUtils, combineClasses } from '@ui-lib/shared'

// Props定义 - 使用共享类型
interface VueButtonProps extends Omit<ButtonProps, 'children'> {}

const props = withDefaults(defineProps<VueButtonProps>(), {
  variant: 'primary',
  size: 'md'
})

// Emits定义
const emit = defineEmits<{
  click: [event: MouseEvent]
}>()

// Ref
const buttonRef = ref<HTMLButtonElement>()

// 样式计算 - 使用共享样式工具
const buttonClasses = computed(() => {
  return combineClasses(
    styleUtils.button.base,
    styleUtils.button.variants[props.variant!],
    styleUtils.button.sizes[props.size!],
    props.className
  )
})

// 事件处理
const handleClick = (event: MouseEvent) => {
  console.log('🐛 Vue按钮被点击!', { variant: props.variant, size: props.size })
  emit('click', event)
}

// 暴露ref给父组件
defineExpose({
  buttonRef
})
</script>

<style scoped>
/* 如果需要组件特定的样式，可以在这里添加 */
</style>

// packages/ui-react/src/components/Button.tsx
import React, { forwardRef } from 'react';
import type { ButtonProps as SharedButtonProps } from '@ui-lib/shared';
import { styleUtils, combineClasses } from '@ui-lib/shared';

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>, 
          Omit<SharedButtonProps, 'children'> {
  children: React.ReactNode;
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = 'primary', size = 'md', className = '', ...props }, ref) => {
    console.log('React Button 渲染:', { variant, size, className });

    const classes = combineClasses(
      styleUtils.button.base,
      styleUtils.button.variants[variant],
      styleUtils.button.sizes[size],
      className
    );

    console.log('最终样式类:', classes);

    return (
      <button
        className={classes}
        ref={ref}
        onClick={(e) => {
          console.log('🐛 React按钮被点击!', { variant, size });
          props.onClick?.(e);
        }}
        {...props}
      />
    );
  }
);

Button.displayName = 'Button';
