// packages/ui-vue/src/components/Radio.vue
<template>
  <label class="inline-flex items-center cursor-pointer">
    <input
      type="radio"
      :class="radioClasses"
      :name="name"
      :value="value"
      :checked="checked"
      :disabled="disabled"
      @change="handleChange"
      ref="radioRef"
    />
    <span v-if="label" :class="labelClasses">
      {{ label }}
    </span>
  </label>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { styleUtils, combineClasses } from '@ui-lib/shared'

// Props定义
interface VueRadioProps {
  label?: string
  name?: string
  value?: string
  checked?: boolean
  disabled?: boolean
  className?: string
}

const props = withDefaults(defineProps<VueRadioProps>(), {
  disabled: false,
  checked: false
})

// Emits定义
const emit = defineEmits<{
  change: [event: Event, value: string | undefined]
}>()

// Ref
const radioRef = ref<HTMLInputElement>()

// 样式计算
const radioClasses = computed(() => {
  return combineClasses(
    styleUtils.radio.base,
    props.className
  )
})

const labelClasses = computed(() => {
  return styleUtils.radio.label
})

// 事件处理
const handleChange = (event: Event) => {
  if (props.disabled) return
  emit('change', event, props.value)
}

// 暴露ref给父组件
defineExpose({
  radioRef
})
</script>

<style scoped>
/* 如果需要组件特定的样式，可以在这里添加 */
</style>

// packages/ui-react/src/components/Radio.tsx
import React from 'react';
import { styleUtils, combineClasses } from '@ui-lib/shared';

export interface RadioProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
  label?: string;
}

export const Radio: React.FC<RadioProps> = ({
  label,
  className,
  ...props
}) => {
  return (
    <label className="inline-flex items-center cursor-pointer">
      <input
        type="radio"
        className={combineClasses(
          styleUtils.radio.base,
          className
        )}
        {...props}
      />
      {label && (
        <span className={styleUtils.radio.label}>
          {label}
        </span>
      )}
    </label>
  );
};

// Radio Group 组件
export interface RadioOption {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface RadioGroupProps {
  options: RadioOption[];
  value?: string;
  onChange: (value: string) => void;
  name: string;
  label?: string;
  direction?: 'horizontal' | 'vertical';
}

export const RadioGroup: React.FC<RadioGroupProps> = ({
  options,
  value,
  onChange,
  name,
  label,
  direction = 'vertical'
}) => {
  return (
    <div>
      {label && (
        <div className="text-sm font-medium text-gray-700 mb-2">
          {label}
        </div>
      )}
      <div className={combineClasses(
        'flex',
        direction === 'horizontal' ? 'flex-row space-x-4' : 'flex-col space-y-2'
      )}>
        {options.map((option) => (
          <Radio
            key={option.value}
            name={name}
            value={option.value}
            checked={value === option.value}
            onChange={() => onChange(option.value)}
            disabled={option.disabled}
            label={option.label}
          />
        ))}
      </div>
    </div>
  );
};
