// packages/ui-vue/src/components/Badge.vue
<template>
  <span :class="[
    'inline-flex items-center rounded-full font-medium',
    sizeClasses[size],
    variantClasses[variant]
  ]">
    <slot />
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { styleUtils } from '@ui-lib/shared'

interface Props {
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger' | 'info'
  size?: 'sm' | 'md' | 'lg'
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'default',
  size: 'md'
})

const sizeClasses = computed(() => ({
  sm: 'px-2 py-0.5 text-xs',
  md: 'px-2.5 py-0.5 text-sm',
  lg: 'px-3 py-1 text-sm'
}))

const variantClasses = computed(() => ({
  default: 'bg-gray-100 text-gray-800',
  primary: styleUtils.badge.variants.primary,
  success: styleUtils.badge.variants.success,
  warning: styleUtils.badge.variants.warning,
  danger: styleUtils.badge.variants.error,
  info: styleUtils.badge.variants.info
}))
</script>

<style scoped>
/* 组件特定样式 */
</style>

// demo-app/src/components/Badge.tsx
import React, { forwardRef } from 'react'
import { BadgeProps } from '../types'
import { cn, getColorClasses, getSizeClasses } from '../utils'

// 徽章组件
export const Badge = forwardRef<HTMLSpanElement, BadgeProps>(
  ({ 
    className,
    variant = 'primary',
    size = 'md',
    dot = false,
    children,
    ...props 
  }, ref) => {
    const baseClasses = 'badge-base'
    const variantClasses = getColorClasses(variant, 'badge')
    const sizeClasses = getSizeClasses(size, 'badge')
    
    if (dot) {
      return (
        <span
          ref={ref}
          className={cn(
            'inline-block w-2 h-2 rounded-full',
            variantClasses,
            className
          )}
          {...props}
        />
      )
    }

    return (
      <span
        ref={ref}
        className={cn(
          baseClasses,
          variantClasses,
          sizeClasses,
          'font-medium',
          className
        )}
        {...props}
      >
        {children}
      </span>
    )
  }
)

Badge.displayName = 'Badge'

export default Badge
